version: '3.8'

services:
  apache:
    image: httpd:2.4
    container_name: apache-server
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs/
    networks:
      - webnet

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
